const mongoose = require("mongoose");
const { getSriLankaTimeString } = require("../utils/time");

const sessionSchema = new mongoose.Schema(
  {
    session_id: {
      type: String,
      required: true,
      unique: true
    },

    // MongoDB stores Date values in UTC.
    // Keep this for sorting, filtering, and duration calculation.
    start_time: {
      type: Date,
      required: true
    },

    // Sri Lankan local display time.
    start_time_sl: {
      type: String,
      required: true
    },

    // MongoDB UTC Date.
    end_time: {
      type: Date,
      default: null
    },

    // Sri Lankan local display time.
    end_time_sl: {
      type: String,
      default: null
    },

    timezone: {
      type: String,
      default: "Asia/Colombo"
    },

    is_active: {
      type: Boolean,
      default: true
    },

    duration_seconds: {
      type: Number,
      default: 0
    },

    // Custom Sri Lankan display timestamps.
    // createdAt and updatedAt generated by Mongoose will still be UTC.
    created_at_sl: {
      type: String,
      default: null
    },

    updated_at_sl: {
      type: String,
      default: null
    }
  },
  {
    timestamps: true
  }
);

sessionSchema.pre("save", function (next) {
  const now = new Date();

  if (this.isNew && !this.created_at_sl) {
    this.created_at_sl = getSriLankaTimeString(now);
  }

  this.updated_at_sl = getSriLankaTimeString(now);

  next();
});

// Do not add session_id index manually.
// unique: true already creates the session_id index.
sessionSchema.index({ is_active: 1, start_time: -1 });
sessionSchema.index({ start_time: -1 });

module.exports = mongoose.model("Session", sessionSchema);